import '@/styles/globals.css'
import theme from '@/styles/theme'
import { ThemeProvider } from 'styled-components'
import 'tailwindcss/tailwind.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <head />
        <body>{children}</body>
      </html>
    </ThemeProvider>
  )
}
